### PR TITLE
Rename mount test to misc test

### PR DESCRIPTION
**Pull request by spuiuk**
The original tests were simple sanity tests used to test mounting the  SMB share using the cifs mount. These tests have now gone beyond those tests and are now used more as io tests. Renaming the tests to reflect this.

### CODE REVIEW

**Comment by spuiuk** [comment]
depends on #51

**Review by Shwetha-Acharya — APPROVED** [review]

**Comment by spuiuk** [comment]
Had to change the name from io to misc. This seems to cause problems loading the conftest.py file from the test directory in the form io.conftest which seems to use the inbuilt module instead. By just changing the name to misc, we no longer hit this issue.

**Review by synarete — APPROVED** [review]
lgtm

**Comment by anoopcs9** [comment]
Can we have this change rebased on top of latest HEAD?

**Review by anoopcs9 — APPROVED** [review]

**Pull request merged**
