### PR TITLE
testcases: simplify test structure

### PR DESCRIPTION
**Pull request by Shwetha-Acharya**
pytest by default runs the functions preceeded with test keyword. As a result, all the required test functions will be executed. Hence, this PR simplifies the code by removing the unnecessary main block.

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
Looks OK to me.

**Review by anoopcs9 — CHANGES_REQUESTED** [review]
lgtm.

I think we have a conflict pending to be resolved.

**Comment by Shwetha-Acharya** [comment]
I just rebased the change after resolving the conflict @anoopcs9

**Review by spuiuk — APPROVED** [review]
ACK

**Pull request merged**
