### PR TITLE
Cleanup testhelper and add pathlib.Path to helper functions.

### PR DESCRIPTION
**Pull request by spuiuk**
Several functions are no longer needed after refactoring of some tests.

Also use pathlib.Path so that tests can be used with windows.

depends on #41

### CODE REVIEW

**Review by synarete — APPROVED** [review]
IMHO, code looks cleaner with this PR.

**Comment by anoopcs9** [comment]
> "=========================== short test summary info ============================",
   **"SKIPPED [1] testcases/mount/test_mount.py:68: got empty parameter set ['test_dir'], function test_mount_premounted at /root/sit-test-cases/testcases/mount/test_mount.py:67",
   "SKIPPED [1] testcases/smbtorture/test_smbtorture.py:129: got empty parameter set ['share_name', 'test'], function test_smbtorture at /root/sit-test-cases/testcases/smbtorture/test_smbtorture.py:128",**
   "PASSED testcases/mount/test_mount.py::test_mount[192.168.123.10-share-cephfs-vfs]",
   "PASSED testcases/mount/test_mount.py::test_mount[192.168.123.12-share-cephfs-vfs]",
   "PASSED testcases/mount/test_mount.py::test_mount[192.168.123.11-share-cephfs-vfs]",
   "PASSED testcases/containers/test_containers.py::test_containers[192.168.123.10-share-cephfs-vfs-smallfiles]",
   "PASSED testcases/consistency/test_consistency.py::test_consistency[192.168.123.11-share-cephfs-vfs]",
   "PASSED testcases/consistency/test_consistency.py::test_consistency[192.168.123.10-share-cephfs-vfs]",
   "PASSED testcases/consistency/test_consistency.py::test_consistency[192.168.123.12-share-cephfs-vfs]",
   "================== 7 passed, 2 skipped in 2216.19s (0:36:56) ===================",

Something's wrong here 😕

**Comment by spuiuk** [comment]
> > "=========================== short test summary info ============================",
> > **"SKIPPED [1] testcases/mount/test_mount.py:68: got empty parameter set ['test_dir'], function test_mount_premounted at /root/sit-test-cases/testcases/mount/test_mount.py:67",

This is fine as we now have support for premounted shares but don't have any set for testing here.

> > "SKIPPED [1] testcases/smbtorture/test_smbtorture.py:129: got empty parameter set ['share_name', 'test'], function test_smbtorture at /root/sit-test-cases/testcases/smbtorture/test_smbtorture.py:128",**

This was a bug. Should be fixed in the latest version of the code.

The patch set is getting closer to being ready for merging.

> 
> Something's wrong here 😕

**Comment by spuiuk** [comment]
Confirmed from the output of the cephfs tests that the temporary files were created as expected and tests run as before. 

The advantage of these changes is that we should now be able to run tests specific for windows using the same helper functions.

**Review by anoopcs9 — APPROVED** [review]
lgtm.

**Review by synarete — APPROVED** [review]
lgtm

**Review by Shwetha-Acharya — APPROVED** [review]

**Pull request merged**
