### PR TITLE
tests/smbtorture: Go through all testcases

### PR DESCRIPTION
**Pull request by spuiuk**
Do not fail the test suite on the failure of the first test. Go through the entire list of tests before deciding to fail.

### CODE REVIEW

**Comment by spuiuk** [comment]
retest this please

**Comment by spuiuk** [comment]
It looks like it is pulling from the wrong repo

From the jenkins info, I can see that it pulls sit-environment instead of sit-test-cases.
```
Preparing to checkout from test repo: https://github.com/samba-in-kubernetes/sit-environment.git, branch pr4
```

**Comment by spuiuk** [comment]
I am using the following job as an example:
https://jenkins-samba.apps.ocp.cloud.ci.centos.org/job/samba_gluster-integration-test-cases/65/console

> It looks like it is pulling from the wrong repo
> 
> From the jenkins info, I can see that it pulls sit-environment instead of sit-test-cases.
> 
> ```
> Preparing to checkout from test repo: https://github.com/samba-in-kubernetes/sit-environment.git, branch pr4
> ```

And this is passed as extra variables when calling make test. 
```
+ EXTRA_VARS='test_repo=https://github.com/samba-in-kubernetes/sit-environment.git test_repo_pr=4'
+ make test
```

This is caused by the following script.
https://github.com/samba-in-kubernetes/samba-centosci/blob/main/jobs/scripts/gluster-integration/gluster-integration.sh#L38

@anoopcs9

**Comment by anoopcs9** [comment]
> This is caused by the following script. https://github.com/samba-in-kubernetes/samba-centosci/blob/main/jobs/scripts/gluster-integration/gluster-integration.sh#L38
> 
> @anoopcs9

Thanks for looking in to it and sorry for the trouble. I have https://github.com/samba-in-kubernetes/samba-centosci/pull/8 to fix the wrong git repository url.

**Comment by spuiuk** [comment]
retest this please

**Comment by spuiuk** [comment]
For the job:
https://jenkins-samba.apps.ocp.cloud.ci.centos.org/job/samba_gluster-integration-test-cases/69/consoleText

We see that the tests continue after we encounter an error when testing samba3.smb2.deny.deny1 and samba3.smb2.deny.deny2.

```

	smb2.credits        
      [OK]
	smb2.deny           
  [Failed]



--Output Start--
Command: /bin/smbtorture --fullname --option=torture:progress=no --option=torture:sharedelay=100000 --option=torture:writetimeupdatedelay=500000 --format=subunit --target=samba3 --user=test1%x //192.168.123.10/gluster-vol-disperse smb2.deny 2>&1|/usr/bin/python3 /root/samba-integration-tests/testcases/smbtorture-test/selftest/filter-subunit --fail-on-empty --prefix='samba3.' --expected-failures=/root/samba-integration-tests/testcases/smbtorture-test/selftest/knownfail --expected-failures=/root/samba-integration-tests/testcases/smbtorture-test/selftest/knownfail.d --flapping=/root/samba-integration-tests/testcases/smbtorture-test/selftest/flapping --flapping=/root/samba-integration-tests/testcases/smbtorture-test/selftest/flapping.d --flapping=/root/samba-integration-tests/testcases/smbtorture-test/selftest/flapping.gluster|/usr/bin/tee -a /tmp/tmp_file_0|/usr/bin/python3 /root/samba-integration-tests/testcases/smbtorture-test/selftest/format-subunit >/dev/null

smbtorture 4.19.0pre1-UNKNOWN
Using seed 1681046119
time: 2023-04-09 13:15:19.469803Z
progress: 2
test: samba3.smb2.deny.deny1
time: 2023-04-09 13:15:19.470578Z
1347: denytest2.dat NTCREATEX_SHARE_ACCESS_READ|NTCREATEX_SHARE_ACCESS_DELETE SEC_FILE_READ_DATA|SEC_FILE_WRITE_DATA    NTCREATEX_SHARE_ACCESS_READ|NTCREATEX_SHARE_ACCESS_WRITE|NTCREATEX_SHARE_ACCESS_DELETE SEC_FILE_READ_DATA    - (correct=R)
time: 2023-04-09 13:15:20.953531Z
failure: samba3.smb2.deny.deny1 [
Exception: ../../source4/torture/smb2/deny.c:491: Expression `res == denytable[i].result' failed: Result - did not match deny table R

]
test: samba3.smb2.deny.deny2
time: 2023-04-09 13:15:20.953547Z
504: denytest2.exe NTCREATEX_SHARE_ACCESS_READ|NTCREATEX_SHARE_ACCESS_DELETE SEC_FILE_READ_DATA|SEC_FILE_WRITE_DATA    NTCREATEX_SHARE_ACCESS_READ|NTCREATEX_SHARE_ACCESS_WRITE|NTCREATEX_SHARE_ACCESS_DELETE SEC_FILE_READ_DATA    - (correct=R)
time: 2023-04-09 13:15:21.649946Z
failure: samba3.smb2.deny.deny2 [
Exception: ../../source4/torture/smb2/deny.c:491: Expression `res == denytable[i].result' failed: Result - did not match deny table R

]

--Output End--
      [OK]
	smb2.lock           
      [OK]
	smb2.mangle         
      [OK]
	smb2.maximum_allowed
      [OK]
	smb2.mkdir          
```
The good news is that the errors above are the only ones noticed during the test.

This PR is ready for merging.

**Review by anoopcs9 — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
