### PR TITLE
testhelper: make _generate_random_bytes public

### PR DESCRIPTION
**Pull request by Shwetha-Acharya**
_generate_random_bytes is a private function in mount_io.py. Made it public by adding it to testhelper.py. With this change generate_random_bytes can be reused in any number of tests.

Fixes: #26

### CODE REVIEW

**Review by synarete — APPROVED** [review]
LGTM

**Review by anoopcs9 — APPROVED** [review]

**Comment by phlogistonjohn** [comment]
I don't care enough to nack this, but I don't really think using this function throughout the code is the best approach. I first recommend surveying what available libraries already exist that might provide a randomized data stream as a pytest fixture.  If no such fixture exists, then I would write one as a fixture.  On top of that I would have the random bytes be available as a standard python type (probably as a readable file-like object or a generator).
Finally, I would prefer to see the random seed explicitly managed - this is the important one and something I think I touched on in the original PR that added this function. It was fine when it was a private func, but it's more important if this starts getting reused all over the place.

**Comment by synarete** [comment]
> I don't care enough to nack this, but I don't really think using this function throughout the code is the best approach. I first recommend surveying what available libraries already exist that might provide a randomized data stream as a pytest fixture. If no such fixture exists, then I would write one as a fixture. On top of that I would have the random bytes be available as a standard python type (probably as a readable file-like object or a generator). Finally, I would prefer to see the random seed explicitly managed - this is the important one and something I think I touched on in the original PR that added this function. It was fine when it was a private func, but it's more important if this starts getting reused all over the place.

@phlogistonjohn Is correct here, and its my fault to fix (probably on-top of this PR). There are 3 different issues here:

0) Have explicit random seed management. Something like [pytest-randomly](https://pypi.org/project/pytest-randomly/)
1) Provide functionality similar to standard `random.randbytes()` where this function does not exist (i.e, CI where python version is less than 3.9)
2) Generate (pseudo) random data for sit-test-cases, without exhaustion the random pool on the host machine or consuming too much CPU (e.g., test 1000 files of 1M random data).

This has been on my TODO list but other things pilled -- I will try to address those soon.

**Review by spuiuk — APPROVED** [review]
ACK

**Comment by spuiuk** [comment]
@synarete , if you approve, we can first commit this PR and when we move to CentOS9, we can modify and commit  PR #29  to use library functions to generate random strings.

**Review by synarete — APPROVED** [review]
LGTM

**Pull request merged**
