### PR TITLE
pytest with randomly via tox

### PR DESCRIPTION
**Pull request by synarete**
Use tox to run pytest. Use pytest-randomly to have better control on random seed upon re-run due to test failure.

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
LGTM generally, I'm just not entirely sure why "pytest" and "sanity" are separate envs, since there appears to be overlap between them. I approve, but would like to add a comment/documentation on what each env is meant to accomplish.

**Comment by synarete** [comment]
> LGTM generally, I'm just not entirely sure why "pytest" and "sanity" are separate envs, since there appears to be overlap between them. I approve, but would like to add a comment/documentation on what each env is meant to accomplish.

It preserves the current existing logic in top-level `Makefile` (I did not want to do such cleanup in this PR).

**Comment by phlogistonjohn** [comment]
OK, thanks. I overlooked that was already the case. My general suggestion to document these different cases still stands, but not for this PR. :-)

**Review by Shwetha-Acharya — APPROVED** [review]

**Comment by spuiuk** [comment]
retest this please

**Comment by spuiuk** [comment]
@synarete , we may need to install tox on the test system in sit-environment before we can commit this change.

From the console output of the test failure.

```
STDERR:

/bin/sh: tox: command not found
make: *** [Makefile:15: test] Error 127


MSG:

non-zero return code
```

**Review by spuiuk — APPROVED** [review]
ACK - but one caveat. We introduce conftest.py but it is never populated. Should we hold on introducing the file until we actually want to add some pytest conf?

**Pull request merged**
